(ns cobot_assembly.actor
  "cobot_assembly clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Collaborative assembly robotics (electronics/semiconductor).

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Cobot
   {:db/ident :cobot_assembly.Cobot/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.Cobot/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/vendor :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/payloadKg :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/reachMm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/axes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Cobot/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Joint
   {:db/ident :cobot_assembly.Joint/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.Joint/cobotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Joint/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Joint/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Joint/rangeDeg :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Joint/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.Joint/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; EndEffector
   {:db/ident :cobot_assembly.EndEffector/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.EndEffector/cobotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.EndEffector/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.EndEffector/gripForceN :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.EndEffector/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.EndEffector/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.EndEffector/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; AssemblyTask
   {:db/ident :cobot_assembly.AssemblyTask/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.AssemblyTask/cobotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.AssemblyTask/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.AssemblyTask/cycleTimeS :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.AssemblyTask/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.AssemblyTask/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.AssemblyTask/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SafetyZone
   {:db/ident :cobot_assembly.SafetyZone/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.SafetyZone/cobotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.SafetyZone/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.SafetyZone/radiusMm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.SafetyZone/speedLimitMmS :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.SafetyZone/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.SafetyZone/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ForceProfile
   {:db/ident :cobot_assembly.ForceProfile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cobot_assembly.ForceProfile/cobotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.ForceProfile/axis :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.ForceProfile/maxForceN :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.ForceProfile/complianceNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.ForceProfile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cobot_assembly.ForceProfile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Cobot" "Joint" "EndEffector" "AssemblyTask" "SafetyZone" "ForceProfile"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "cobot_assembly: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "cobot_assembly: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "cobot_assembly: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Cobot ────────────────────────────────────────────────────────────────
(defn create-cobot
  "Create a Cobot."
  [port data]
  (require-fields data ["name" "vendor"])
  (let [id (new-id "cob_cob")
        e {:db/id id
           :cobot_assembly.Cobot/id id
           :cobot_assembly.Cobot/name (get data :name)
           :cobot_assembly.Cobot/vendor (get data :vendor)
           :cobot_assembly.Cobot/payloadKg (as-double (get data :payloadKg))
           :cobot_assembly.Cobot/reachMm (as-double (get data :reachMm))
           :cobot_assembly.Cobot/axes (as-long (get data :axes))
           :cobot_assembly.Cobot/createdAt (now)
           :cobot_assembly.Cobot/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cobots
  "List Cobot with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cobots port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.Cobot/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.Cobot/name :cobot_assembly.Cobot/vendor :cobot_assembly.Cobot/payloadKg :cobot_assembly.Cobot/reachMm :cobot_assembly.Cobot/axes])]
     (paginate rows opts))))

(defn get-cobot
  "Retrieve a Cobot by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cobot port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cobot
  "Update a Cobot; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :cobot_assembly.Cobot/name (get data :name)]))
                   (cond-> (contains? data :vendor) (conj [:db/add id :cobot_assembly.Cobot/vendor (get data :vendor)]))
                   (cond-> (contains? data :payloadKg) (conj [:db/add id :cobot_assembly.Cobot/payloadKg (as-double (get data :payloadKg))]))
                   (cond-> (contains? data :reachMm) (conj [:db/add id :cobot_assembly.Cobot/reachMm (as-double (get data :reachMm))]))
                   (cond-> (contains? data :axes) (conj [:db/add id :cobot_assembly.Cobot/axes (as-long (get data :axes))]))
                   (conj [:db/add id :cobot_assembly.Cobot/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cobot
  "Delete a Cobot."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Joint ────────────────────────────────────────────────────────────────
(defn create-joint
  "Create a Joint."
  [port data]
  (require-fields data ["index" "type"])
  (let [id (new-id "cob_joi")
        e {:db/id id
           :cobot_assembly.Joint/id id
           :cobot_assembly.Joint/cobotId (get data :cobotId)
           :cobot_assembly.Joint/index (as-long (get data :index))
           :cobot_assembly.Joint/type (get data :type)
           :cobot_assembly.Joint/rangeDeg (as-double (get data :rangeDeg))
           :cobot_assembly.Joint/createdAt (now)
           :cobot_assembly.Joint/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-joints
  "List Joint with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-joints port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.Joint/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.Joint/cobotId :cobot_assembly.Joint/index :cobot_assembly.Joint/type :cobot_assembly.Joint/rangeDeg])]
     (paginate rows opts))))

(defn get-joint
  "Retrieve a Joint by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-joint port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :cobotId) (get rec :cobot_assembly.Joint/cobotId))
         (assoc :cobotId-obj (-pull port (get rec :cobot_assembly.Joint/cobotId))))))))

(defn update-joint
  "Update a Joint; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :cobotId) (conj [:db/add id :cobot_assembly.Joint/cobotId (get data :cobotId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :cobot_assembly.Joint/index (as-long (get data :index))]))
                   (cond-> (contains? data :type) (conj [:db/add id :cobot_assembly.Joint/type (get data :type)]))
                   (cond-> (contains? data :rangeDeg) (conj [:db/add id :cobot_assembly.Joint/rangeDeg (as-double (get data :rangeDeg))]))
                   (conj [:db/add id :cobot_assembly.Joint/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-joint
  "Delete a Joint."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── EndEffector ────────────────────────────────────────────────────────────────
(defn create-end-effector
  "Create a EndEffector."
  [port data]
  (require-fields data ["kind" "gripForceN"])
  (let [id (new-id "cob_end")
        e {:db/id id
           :cobot_assembly.EndEffector/id id
           :cobot_assembly.EndEffector/cobotId (get data :cobotId)
           :cobot_assembly.EndEffector/kind (get data :kind)
           :cobot_assembly.EndEffector/gripForceN (as-double (get data :gripForceN))
           :cobot_assembly.EndEffector/status (get data :status)
           :cobot_assembly.EndEffector/createdAt (now)
           :cobot_assembly.EndEffector/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-end-effectors
  "List EndEffector with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-end-effectors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.EndEffector/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.EndEffector/cobotId :cobot_assembly.EndEffector/kind :cobot_assembly.EndEffector/gripForceN :cobot_assembly.EndEffector/status])]
     (paginate rows opts))))

(defn get-end-effector
  "Retrieve a EndEffector by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-end-effector port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :cobotId) (get rec :cobot_assembly.EndEffector/cobotId))
         (assoc :cobotId-obj (-pull port (get rec :cobot_assembly.EndEffector/cobotId))))))))

(defn update-end-effector
  "Update a EndEffector; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :cobotId) (conj [:db/add id :cobot_assembly.EndEffector/cobotId (get data :cobotId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :cobot_assembly.EndEffector/kind (get data :kind)]))
                   (cond-> (contains? data :gripForceN) (conj [:db/add id :cobot_assembly.EndEffector/gripForceN (as-double (get data :gripForceN))]))
                   (cond-> (contains? data :status) (conj [:db/add id :cobot_assembly.EndEffector/status (get data :status)]))
                   (conj [:db/add id :cobot_assembly.EndEffector/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-end-effector
  "Delete a EndEffector."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── AssemblyTask ────────────────────────────────────────────────────────────────
(defn create-assembly-task
  "Create a AssemblyTask."
  [port data]
  (require-fields data ["name" "cycleTimeS"])
  (let [id (new-id "cob_ass")
        e {:db/id id
           :cobot_assembly.AssemblyTask/id id
           :cobot_assembly.AssemblyTask/cobotId (get data :cobotId)
           :cobot_assembly.AssemblyTask/name (get data :name)
           :cobot_assembly.AssemblyTask/cycleTimeS (as-double (get data :cycleTimeS))
           :cobot_assembly.AssemblyTask/status (get data :status)
           :cobot_assembly.AssemblyTask/createdAt (now)
           :cobot_assembly.AssemblyTask/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-assembly-tasks
  "List AssemblyTask with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-assembly-tasks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.AssemblyTask/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.AssemblyTask/cobotId :cobot_assembly.AssemblyTask/name :cobot_assembly.AssemblyTask/cycleTimeS :cobot_assembly.AssemblyTask/status])]
     (paginate rows opts))))

(defn get-assembly-task
  "Retrieve a AssemblyTask by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-assembly-task port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :cobotId) (get rec :cobot_assembly.AssemblyTask/cobotId))
         (assoc :cobotId-obj (-pull port (get rec :cobot_assembly.AssemblyTask/cobotId))))))))

(defn update-assembly-task
  "Update a AssemblyTask; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :cobotId) (conj [:db/add id :cobot_assembly.AssemblyTask/cobotId (get data :cobotId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :cobot_assembly.AssemblyTask/name (get data :name)]))
                   (cond-> (contains? data :cycleTimeS) (conj [:db/add id :cobot_assembly.AssemblyTask/cycleTimeS (as-double (get data :cycleTimeS))]))
                   (cond-> (contains? data :status) (conj [:db/add id :cobot_assembly.AssemblyTask/status (get data :status)]))
                   (conj [:db/add id :cobot_assembly.AssemblyTask/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-assembly-task
  "Delete a AssemblyTask."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SafetyZone ────────────────────────────────────────────────────────────────
(defn create-safety-zone
  "Create a SafetyZone."
  [port data]
  (require-fields data ["kind" "radiusMm"])
  (let [id (new-id "cob_saf")
        e {:db/id id
           :cobot_assembly.SafetyZone/id id
           :cobot_assembly.SafetyZone/cobotId (get data :cobotId)
           :cobot_assembly.SafetyZone/kind (get data :kind)
           :cobot_assembly.SafetyZone/radiusMm (as-double (get data :radiusMm))
           :cobot_assembly.SafetyZone/speedLimitMmS (as-double (get data :speedLimitMmS))
           :cobot_assembly.SafetyZone/createdAt (now)
           :cobot_assembly.SafetyZone/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-safety-zones
  "List SafetyZone with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-safety-zones port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.SafetyZone/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.SafetyZone/cobotId :cobot_assembly.SafetyZone/kind :cobot_assembly.SafetyZone/radiusMm :cobot_assembly.SafetyZone/speedLimitMmS])]
     (paginate rows opts))))

(defn get-safety-zone
  "Retrieve a SafetyZone by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-safety-zone port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :cobotId) (get rec :cobot_assembly.SafetyZone/cobotId))
         (assoc :cobotId-obj (-pull port (get rec :cobot_assembly.SafetyZone/cobotId))))))))

(defn update-safety-zone
  "Update a SafetyZone; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :cobotId) (conj [:db/add id :cobot_assembly.SafetyZone/cobotId (get data :cobotId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :cobot_assembly.SafetyZone/kind (get data :kind)]))
                   (cond-> (contains? data :radiusMm) (conj [:db/add id :cobot_assembly.SafetyZone/radiusMm (as-double (get data :radiusMm))]))
                   (cond-> (contains? data :speedLimitMmS) (conj [:db/add id :cobot_assembly.SafetyZone/speedLimitMmS (as-double (get data :speedLimitMmS))]))
                   (conj [:db/add id :cobot_assembly.SafetyZone/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-safety-zone
  "Delete a SafetyZone."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ForceProfile ────────────────────────────────────────────────────────────────
(defn create-force-profile
  "Create a ForceProfile."
  [port data]
  (require-fields data ["axis" "maxForceN"])
  (let [id (new-id "cob_for")
        e {:db/id id
           :cobot_assembly.ForceProfile/id id
           :cobot_assembly.ForceProfile/cobotId (get data :cobotId)
           :cobot_assembly.ForceProfile/axis (get data :axis)
           :cobot_assembly.ForceProfile/maxForceN (as-double (get data :maxForceN))
           :cobot_assembly.ForceProfile/complianceNm (as-double (get data :complianceNm))
           :cobot_assembly.ForceProfile/createdAt (now)
           :cobot_assembly.ForceProfile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-force-profiles
  "List ForceProfile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-force-profiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cobot_assembly.ForceProfile/id))
         rows (apply-filters rows (:filter opts) [:cobot_assembly.ForceProfile/cobotId :cobot_assembly.ForceProfile/axis :cobot_assembly.ForceProfile/maxForceN :cobot_assembly.ForceProfile/complianceNm])]
     (paginate rows opts))))

(defn get-force-profile
  "Retrieve a ForceProfile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-force-profile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :cobotId) (get rec :cobot_assembly.ForceProfile/cobotId))
         (assoc :cobotId-obj (-pull port (get rec :cobot_assembly.ForceProfile/cobotId))))))))

(defn update-force-profile
  "Update a ForceProfile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :cobotId) (conj [:db/add id :cobot_assembly.ForceProfile/cobotId (get data :cobotId)]))
                   (cond-> (contains? data :axis) (conj [:db/add id :cobot_assembly.ForceProfile/axis (get data :axis)]))
                   (cond-> (contains? data :maxForceN) (conj [:db/add id :cobot_assembly.ForceProfile/maxForceN (as-double (get data :maxForceN))]))
                   (cond-> (contains? data :complianceNm) (conj [:db/add id :cobot_assembly.ForceProfile/complianceNm (as-double (get data :complianceNm))]))
                   (conj [:db/add id :cobot_assembly.ForceProfile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-force-profile
  "Delete a ForceProfile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/cobots" :op :create :entity "Cobot"}
   {:method "GET" :path "/v1/cobots" :op :list :entity "Cobot"}
   {:method "GET" :path "/v1/cobots/:id" :op :get :entity "Cobot"}
   {:method "PATCH" :path "/v1/cobots/:id" :op :update :entity "Cobot"}
   {:method "DELETE" :path "/v1/cobots/:id" :op :delete :entity "Cobot"}
   {:method "POST" :path "/v1/joints" :op :create :entity "Joint"}
   {:method "GET" :path "/v1/joints" :op :list :entity "Joint"}
   {:method "GET" :path "/v1/joints/:id" :op :get :entity "Joint"}
   {:method "PATCH" :path "/v1/joints/:id" :op :update :entity "Joint"}
   {:method "DELETE" :path "/v1/joints/:id" :op :delete :entity "Joint"}
   {:method "POST" :path "/v1/endeffectors" :op :create :entity "EndEffector"}
   {:method "GET" :path "/v1/endeffectors" :op :list :entity "EndEffector"}
   {:method "GET" :path "/v1/endeffectors/:id" :op :get :entity "EndEffector"}
   {:method "PATCH" :path "/v1/endeffectors/:id" :op :update :entity "EndEffector"}
   {:method "DELETE" :path "/v1/endeffectors/:id" :op :delete :entity "EndEffector"}
   {:method "POST" :path "/v1/assemblytasks" :op :create :entity "AssemblyTask"}
   {:method "GET" :path "/v1/assemblytasks" :op :list :entity "AssemblyTask"}
   {:method "GET" :path "/v1/assemblytasks/:id" :op :get :entity "AssemblyTask"}
   {:method "PATCH" :path "/v1/assemblytasks/:id" :op :update :entity "AssemblyTask"}
   {:method "DELETE" :path "/v1/assemblytasks/:id" :op :delete :entity "AssemblyTask"}
   {:method "POST" :path "/v1/safetyzones" :op :create :entity "SafetyZone"}
   {:method "GET" :path "/v1/safetyzones" :op :list :entity "SafetyZone"}
   {:method "GET" :path "/v1/safetyzones/:id" :op :get :entity "SafetyZone"}
   {:method "PATCH" :path "/v1/safetyzones/:id" :op :update :entity "SafetyZone"}
   {:method "DELETE" :path "/v1/safetyzones/:id" :op :delete :entity "SafetyZone"}
   {:method "POST" :path "/v1/forceprofiles" :op :create :entity "ForceProfile"}
   {:method "GET" :path "/v1/forceprofiles" :op :list :entity "ForceProfile"}
   {:method "GET" :path "/v1/forceprofiles/:id" :op :get :entity "ForceProfile"}
   {:method "PATCH" :path "/v1/forceprofiles/:id" :op :update :entity "ForceProfile"}
   {:method "DELETE" :path "/v1/forceprofiles/:id" :op :delete :entity "ForceProfile"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"cobots" {:create create-cobot :list list-cobots :get get-cobot :update update-cobot :delete delete-cobot}
   "joints" {:create create-joint :list list-joints :get get-joint :update update-joint :delete delete-joint}
   "endeffectors" {:create create-end-effector :list list-end-effectors :get get-end-effector :update update-end-effector :delete delete-end-effector}
   "assemblytasks" {:create create-assembly-task :list list-assembly-tasks :get get-assembly-task :update update-assembly-task :delete delete-assembly-task}
   "safetyzones" {:create create-safety-zone :list list-safety-zones :get get-safety-zone :update update-safety-zone :delete delete-safety-zone}
   "forceprofiles" {:create create-force-profile :list list-force-profiles :get get-force-profile :update update-force-profile :delete delete-force-profile}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "cobot_assembly-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
